### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by kisyular** [kisyular/MI-449-SS17-740-js-objects-T4W3KQ#1]
@chrisvfritz Can you take a look at this? It's [hosted here](https://mi-449-ss17-740-js-objects-t4w3kq-kisyular.surge.sh/) and meets the following criteria:

- [x] Your app builds on [these files](https://gist.github.com/chrisvfritz/3bd1b8d8e5b0d1ea2278ffbc561de047) (you can make changes to any of them)
- [x] When the `requestedJokeInput` has a value matching the key of an existing joke, the `jokeBox` HTML is updated [in this format](https://gist.github.com/chrisvfritz/4def3c246dfb931ecb57384a5639af99)
- [x] When the `requestedJokeInput` does _not_ match an existing joke, the `jokeBox` content is updated to `No matching joke found.`
- [x] When the `Remember this joke!` button is clicked, a new joke is saved (or overwritten) in the `jokes` object, using the data in the associated `input`/`textarea` elements
- [x] When the `Forget about it!` button is clicked, the joke with that key (if any) is deleted from the `jokes` object
- [x] Whenever the `jokes` object changes, the new version is saved in `localStorage` and used whenever the user visits the page again
- [x] It's impossible for an error to ever occur in the JavaScript console

**Comment by chrisvfritz** [comment]
This is looking very nice! 👏  I only see a few areas for improvement:

### Repeated code

I notice a couple instances of this code exactly:

``` js
var stringifiedData = JSON.stringify(jokesStore)
window.localStorage.setItem('storedData', stringifiedData)
```

When we repeat the same code more than once, it's often a sign that it should be in its own function. In this case however, I notice another pattern. We also call `updateJokesMenu` afterwards every time:

``` js
updateJokesMenu()
```

That makes me think that we really might want an `updateJokes` function that saves the new jokes to localStorage and then calls `updateJokesMenu()`, since we'll never want the page to be out of sync with the jokes.

### JS Standard style violations

I'm seeing a few style violations of JS Standard. Let me know if you're having any issues getting the plugin to work in Atom and I'll be happy to help. 🙂

**Comment by kisyular** [comment]
@chrisvfritz, hi. 

Thanks for the feedback. I have successfully updated the the code to remove the repeating code by creating a new function _updateJokes ()_. I have also fixed the styling issue with my js file. Kindly take a look and let me know if I need to make more changes. 

Thank you

**Comment by chrisvfritz** [comment]
Wonderful! 🎉 :shipit: Fantastic work here. 😄
